// Generated by scripts/generate-service-settings.js from package.json. Do not edit.
export const SETTINGS_CATALOG = [
  {
    "key": "accountService.enabled",
    "type": "boolean",
    "default": true,
    "description": "Use the shared account service as the source of usage, account state, rotation, credentials and runtime ownership. Both background and embedded service modes keep profiles in the service home. Off: the plugin runs the same shared engine directly, including local usage collection and rotation scores. Turning this off does not stop or uninstall a running background service; use Account Service… for that."
  },
  {
    "key": "accountService.background",
    "type": "boolean",
    "default": true,
    "description": "**Run the account service in the background.** On: the extension offers to install it under `~/.ai-usage` and register it to start when you sign in, so keep-alives and rotation keep running while VS Code is closed and the `ai-usage` command works in any terminal. Off, or until it is installed: the same service runs inside a VS Code window (the first window hosts it, the others use it, and another takes over when that window closes) and stops with VS Code; nothing is installed and nothing runs in the background. Turning this off does not uninstall an installed service; use **AI Usage: Account Service… → Uninstall**."
  },
  {
    "key": "chatChips.agentsWindow",
    "type": "boolean",
    "default": true,
    "description": "Also show the usage chips beneath the chat input in the **Agents** (sessions) window. The Agents window only runs extensions installed locally and listed in `#extensions.supportAgentsWindow#` (local user settings). The extension there runs on your local computer and shows the logins found **there**, also for remote sessions; a chat whose agent is not signed in locally gets an `n/a` chip. [Enable AI Usage there](command:aiUsage.enableAgentsWindow) · [Open user settings.json](command:workbench.action.openSettingsJson) · [Setup guide](command:aiUsage.openAgentsWindowSetup) · [README](https://github.com/p0l0us/ai-usage-vscode-plugin#agents-sessions-window)."
  },
  {
    "key": "chatChips.enabled",
    "type": "boolean",
    "default": true,
    "description": "Show the current chat's agent usage (Copilot, Claude Code, Codex) as chips beneath the chat input, next to the context usage indicator, e.g. \"Claude 4% (5h)\" \"26% (7d)\". Click a chip to open that agent's details panel. The hover of a chip only repeats its text; VS Code allows no richer tooltip there."
  },
  {
    "key": "chatTokens.enabled",
    "type": "boolean",
    "default": true,
    "description": "Show a chip with tokens consumed by the newest Claude or Codex chat in the current workspace. The value comes from the local agent session log, is compactly rounded in the chip, and opens an exact breakdown when clicked. Copilot does not expose per-chat token telemetry to extensions."
  },
  {
    "key": "updateIntervalMinutes",
    "type": "number",
    "min": 0.25,
    "default": 1,
    "description": "How often (minutes) every window re-reads the shared cache and redraws the status bar and chat chips. Applies to all sources (service API, CLI, session log). The sources themselves are only called when the cached reading is older than the per-service `checkIntervalMinutes`."
  },
  {
    "key": "statusBar.labels",
    "type": "enum",
    "values": [
      "none",
      "nameOnly",
      "iconOnly",
      "iconAndName"
    ],
    "default": "iconOnly",
    "description": "What precedes the figures in each status bar item. The tooltip and the details always show the full name."
  },
  {
    "key": "statusBar.enabled",
    "type": "boolean",
    "default": true,
    "description": "Show usage items in the status bar. When off (or when VS Code's status bar is hidden), the chat chips take over in regular windows if `#aiUsage.chatChips.workbench#` is `whenNoStatusBar`."
  },
  {
    "key": "chatChips.workbench",
    "type": "enum",
    "values": [
      "whenNoStatusBar",
      "always",
      "never"
    ],
    "default": "whenNoStatusBar",
    "description": "When to show chips beneath the chat input in a regular VS Code window. The Agents window has no status bar, so chips there are governed only by `#aiUsage.chatChips.agentsWindow#`."
  },
  {
    "key": "statusBar.usage",
    "type": "enum",
    "values": [
      "simple",
      "rich"
    ],
    "default": "rich",
    "description": "How much of the usage each status bar item shows. Hover for the full breakdown either way."
  },
  {
    "key": "chatChips.labels",
    "type": "enum",
    "values": [
      "none",
      "name"
    ],
    "default": "name",
    "description": "What precedes the figures in the chat chips. Chips cannot show the vendor icon: VS Code drops the text of a toolbar item that has an icon."
  },
  {
    "key": "chatChips.usage",
    "type": "enum",
    "values": [
      "simple",
      "rich"
    ],
    "default": "rich",
    "description": "How much of the usage the chat chips show. Copilot has a single monthly window, so both look the same for it."
  },
  {
    "key": "privateProfiles.enabled",
    "type": "boolean",
    "default": true,
    "description": "**Private profiles.** Keep saved Claude and Codex profiles privately in the account service's own file (`~/.ai-usage/profiles.json`), the usual place, listed in every window on this host. When project profiles are enabled too and a local folder is open, saving a profile asks which kind to create; with only one kind possible, that kind is used without asking. Turning this off only stops new private profiles; existing ones stay listed. Mirrored to the service's `privateProfiles.enabled` setting."
  },
  {
    "key": "projectProfiles.enabled",
    "type": "boolean",
    "default": true,
    "description": "**Project profiles.** Also load and save Claude and Codex profiles in each open workspace folder's project profile file (`#aiUsage.projectProfiles.file#`, `.ai-usage.profiles.json` by default), login included, so they travel with the project and are listed whenever it is open. Known limitation: the account service is one per host, so the project profiles of every folder open in any connected window are merged into one list, and a project can be used with another open project's profiles. The file holds login tokens in plain text; when the folder is a Git repository, it is added to its `.gitignore`. Mirrored to the service's `projectProfiles.enabled` setting."
  },
  {
    "key": "projectProfiles.file",
    "type": "string",
    "default": ".ai-usage.profiles.json",
    "description": "**Project profile file.** Path of the file that holds a project's profiles, relative to each workspace folder. It has the format of a profile export and is written with mode `0600`; when the folder is a Git repository, the path is added to its `.gitignore` the first time a project profile is saved there. Mirrored to the service's `projectProfiles.file` setting."
  },
  {
    "key": "claude.enabled",
    "type": "boolean",
    "default": true,
    "description": "Show live Claude Code rate-limit usage in the status bar when a Claude Code login is found (~/.claude/.credentials.json or $CLAUDE_CONFIG_DIR)."
  },
  {
    "key": "claude.statusBar.accountNumber",
    "type": "boolean",
    "default": true,
    "description": "**Show the Claude account number in the status bar.** Puts the active saved profile's position in the Accounts list between the icon and the figures, e.g. `#2 17% (3h)`. Shown only when at least two Claude profiles are saved and the active login is one of them."
  },
  {
    "key": "claude.source",
    "type": "enum",
    "values": [
      "auto",
      "both",
      "cli",
      "api",
      "accountFile"
    ],
    "default": "auto",
    "description": "Where Claude usage is read from. `auto` chooses the cheapest fresh usable source and falls back to more costly available sources; explicit source modes remain available."
  },
  {
    "key": "claude.checkIntervalMinutes",
    "type": "number",
    "min": 0.25,
    "default": 30,
    "description": "How often (minutes) Claude usage is checked; defaults to 30 minutes. In `auto` this is also the maximum age of a usable cached or local reading. Existing explicit intervals are preserved. Claude accepts fractional minutes down to 0.25; endpoint calls still respect the shared API budget and backoff. The separate account-file interval in seconds applies only to `accountFile` and `both`."
  },
  {
    "key": "claude.accountFile.checkIntervalSeconds",
    "type": "number",
    "min": 5,
    "default": 15,
    "description": "How often (seconds) the account file is re-read, when `#aiUsage.claude.source#` is `accountFile` or `both`. It is a local file read with no rate limit of its own, so this can be much shorter than `#aiUsage.claude.checkIntervalMinutes#`; to actually see updates this often, also lower `#aiUsage.updateIntervalMinutes#` (it accepts fractional minutes, e.g. 0.25 for 15 seconds)."
  },
  {
    "key": "claude.api.minIntervalSeconds",
    "type": "number",
    "min": 0,
    "max": 600,
    "default": 30,
    "description": "**Smallest gap between two calls to Anthropic's usage endpoint**, counted across all open windows, every saved account and manual refreshes. Anthropic rate-limits this endpoint and does not document the limit; the extension also honours a stricter one when a response advertises it (`anthropic-ratelimit-requests-*` or `Retry-After`). A refresh that arrives too early shows the cached reading instead of calling out. `0` leaves only the service's own limits."
  },
  {
    "key": "claude.keepAlive.enabled",
    "type": "boolean",
    "default": false,
    "description": "**Account keep-alive and usage collection.** Periodically send the small `#aiUsage.claude.keepAlive.model#` prompt with every saved Claude account, including inactive ones, and record the usage each one reports. Accounts are staged in `#aiUsage.claude.keepAlive.home#`, never in the native CLI home."
  },
  {
    "key": "claude.autoRotate.enabled",
    "type": "boolean",
    "default": false,
    "description": "**Automatic Claude account rotation.** Switch the active account as soon as its usage reaches `#aiUsage.claude.autoRotate.fiveHourThresholdPercent#` in the 5-hour window or `#aiUsage.claude.autoRotate.weeklyThresholdPercent#` in a weekly window, or proactively (`#aiUsage.claude.autoRotate.trigger#`). The account switched to is chosen by `#aiUsage.claude.autoRotate.strategy#` and must be below both thresholds. Requires at least two saved profiles. See [Rotation strategies and thresholds](https://github.com/p0l0us/ai-usage-vscode-plugin/blob/main/docs/CONFIGURATION.md#rotation-strategies-and-thresholds)."
  },
  {
    "key": "claude.keepAlive.periodHours",
    "type": "number",
    "min": 0.25,
    "default": 2,
    "description": "**Claude keep-alive period in hours.** Each saved Claude account is checked once per period. The schedule persists across window restarts."
  },
  {
    "key": "claude.keepAlive.model",
    "type": "string",
    "default": "haiku",
    "description": "Subscription model used for the small keep-alive request (default: haiku)."
  },
  {
    "key": "claude.autoRotate.fiveHourThresholdPercent",
    "type": "number",
    "min": 1,
    "max": 100,
    "default": 95,
    "description": "**Claude 5-hour rotation threshold.** Rotate when the 5-hour window reaches this percentage (usage ≥ threshold). An account can only be switched to while its 5-hour usage is below it."
  },
  {
    "key": "claude.autoRotate.weeklyThresholdPercent",
    "type": "number",
    "min": 1,
    "max": 100,
    "default": 99.5,
    "description": "**Claude weekly rotation threshold.** Rotate when a weekly window reaches this percentage (usage ≥ threshold): the all-models `7d` window, and `7d Fable` when `#aiUsage.claude.autoRotate.modelLimits#` counts it. An account can only be switched to while every counted weekly window is below it."
  },
  {
    "key": "claude.autoRotate.modelLimits",
    "type": "enum",
    "values": [
      "auto",
      "always",
      "never"
    ],
    "default": "auto",
    "description": "**Claude Fable limit in rotation.** Whether the `7d Fable` window blocks an account and counts when ranking accounts. `auto` reads `model` from Claude Code's `settings.json`."
  },
  {
    "key": "claude.autoRotate.strategy",
    "type": "enum",
    "values": [
      "soonestReset",
      "evenPace",
      "leastWaste",
      "sequential"
    ],
    "default": "soonestReset",
    "description": "**Claude rotation strategy.** How automatic rotation chooses the account to switch to. Ranking uses the readings already collected for each account (see `#aiUsage.claude.keepAlive.enabled#`); the chosen account is always read again and sent a keep-alive before switching."
  },
  {
    "key": "claude.autoRotate.trigger",
    "type": "enum",
    "values": [
      "limit",
      "proactive"
    ],
    "default": "limit",
    "description": "**Claude rotation trigger.** When automatic rotation switches accounts."
  },
  {
    "key": "claude.autoRotate.minStayMinutes",
    "type": "number",
    "min": 5,
    "default": 30,
    "description": "**Claude minimum stay before a proactive switch, in minutes.** With the `proactive` trigger, an account that became active, automatically or by hand, is kept at least this long unless it reaches its limit."
  },
  {
    "key": "claude.keepAlive.home",
    "type": "string",
    "default": "~/.claude-tmp",
    "description": "Dedicated CLI home for background account checks. Supports ~; relative paths resolve from your user home. Must be separate from the native CLI home."
  },
  {
    "key": "claude.cliPath",
    "type": "string",
    "default": "claude",
    "description": "Command or full path of the Claude CLI, used when `aiUsage.claude.source` is `cli` and for account keep-alives. Bare names are searched on PATH and in common install directories."
  },
  {
    "key": "claude.advanced.rotationDiagnostics",
    "type": "boolean",
    "default": false,
    "description": "Advanced: show every saved account’s rotation score, candidate order, eligibility and the reason the current account is kept in the status bar tooltip. Computed by the service when enabled, or by the same shared engine inside VS Code otherwise."
  },
  {
    "key": "claudeConfig.env.maxConcurrentSubagents",
    "type": "integer",
    "min": 1,
    "nullable": true,
    "default": null,
    "description": "Maximum number of subagents (Agent tool) Claude Code runs at the same time; Claude Code defaults to 20. Written as `env.CLAUDE_CODE_MAX_CONCURRENT_SUBAGENTS` in Claude Code user settings (`settings.json` in `$CLAUDE_CONFIG_DIR`, default `~/.claude`) when AI Usage starts and whenever this setting changes. New Claude Code sessions use it; running sessions keep the old value until restarted. Needs Claude Code 2.1.217 or later. A higher cap does not raise your account usage limit. Leave empty (`null`) to keep whatever `settings.json` already says; clearing the setting later does not remove the value from the file."
  },
  {
    "key": "claudeConfig.env.workflowMaxConcurrentAgents",
    "type": "integer",
    "min": 1,
    "max": 256,
    "nullable": true,
    "default": null,
    "description": "Maximum number of workflow agents Claude Code runs at the same time (at most 256); Claude Code defaults to 16, or fewer on machines with few CPUs. Written as `env.CLAUDE_CODE_WORKFLOW_MAX_CONCURRENT_AGENTS` in Claude Code user settings. Needs Claude Code 2.1.269 or later. Leave empty (`null`) to keep whatever `settings.json` already says; clearing the setting later does not remove the value from the file."
  },
  {
    "key": "codex.enabled",
    "type": "boolean",
    "default": true,
    "description": "Show live Codex rate-limit usage in the status bar when a Codex login is found (~/.codex/auth.json or $CODEX_HOME)."
  },
  {
    "key": "codex.statusBar.accountNumber",
    "type": "boolean",
    "default": true,
    "description": "**Show the Codex account number in the status bar.** Puts the active saved profile's position in the Accounts list between the icon and the figures, e.g. `#2 17% (3h)`. Shown only when at least two Codex profiles are saved and the active login is one of them."
  },
  {
    "key": "codex.source",
    "type": "enum",
    "values": [
      "auto",
      "both",
      "cli",
      "api",
      "sessionLog"
    ],
    "default": "auto",
    "description": "Where Codex usage is read from. `auto` chooses the cheapest fresh usable source and falls back to more costly available sources; explicit source modes remain available."
  },
  {
    "key": "codex.cliPath",
    "type": "string",
    "default": "codex",
    "description": "Command or full path of the Codex CLI used when `#aiUsage.codex.source#` is `cli`. Bare names are searched on PATH and in common install directories."
  },
  {
    "key": "codex.checkIntervalMinutes",
    "type": "number",
    "min": 1,
    "default": 30,
    "description": "How often (minutes) Codex usage is checked; defaults to 30 minutes. In `auto` this is also the maximum age of a usable cached or local reading. Existing explicit intervals are preserved. With `both` this is also the maximum age of a session-log record before the usage endpoint fills the gap."
  },
  {
    "key": "codex.keepAlive.enabled",
    "type": "boolean",
    "default": false,
    "description": "**Account keep-alive and usage collection.** Periodically send the small `#aiUsage.codex.keepAlive.model#` prompt with every saved Codex account, including inactive ones, and record the usage each one reports. Accounts are staged in `#aiUsage.codex.keepAlive.home#`, never in the native CLI home."
  },
  {
    "key": "codex.autoRotate.enabled",
    "type": "boolean",
    "default": false,
    "description": "**Automatic Codex account rotation.** Switch when the active account reaches a 5-hour or weekly threshold, or proactively if configured. The selected strategy chooses among eligible saved accounts; reset-aware timing avoids short-lived switches just before a quota reset. Requires at least two saved profiles. See [Rotation strategies and thresholds](https://github.com/p0l0us/ai-usage-vscode-plugin/blob/main/docs/ROTATION.md)."
  },
  {
    "key": "codex.autoReset.enabled",
    "type": "boolean",
    "default": true,
    "description": "**Automatically use earned Codex rate-limit resets.** When Codex reports an available reset credit and the active saved account is at a quota limit, the account service can redeem one through Codex app-server. It waits for a natural reset within five minutes, considers other saved accounts and the rotation strategy, and avoids letting a reported credit expire unused. Only provider-reported credits are used; the setting can be turned off independently of account rotation."
  },
  {
    "key": "codex.autoReset.confirmationRequired",
    "type": "boolean",
    "default": false,
    "description": "Require confirmation before redeeming an earned Codex reset credit. The shared engine supplies and revalidates the proposed redemption; one connected editor may approve it. Without an approving editor, no credit is redeemed. Off preserves automatic redemption. This does not enable auto-reset by itself."
  },
  {
    "key": "codex.autoRotate.resetAware",
    "type": "boolean",
    "default": true,
    "description": "**Reset-aware Codex rotation.** When on, automatic rotation waits if the active account's limiting quota resets naturally within 5 minutes, and skips a candidate whose reported 5-hour or weekly quota resets within 5 minutes. The service rechecks after the reset; a manual Rotate now bypasses this wait. Applies with every strategy. Earned credit redemption is controlled separately by `#aiUsage.codex.autoReset.enabled#`."
  },
  {
    "key": "codex.keepAlive.periodHours",
    "type": "number",
    "min": 0.25,
    "default": 6,
    "description": "**Codex keep-alive period in hours.** Each saved Codex account is checked once per period. The schedule persists across window restarts."
  },
  {
    "key": "codex.keepAlive.model",
    "type": "string",
    "default": "gpt-5.6-luna",
    "description": "Subscription model used for the small keep-alive request (default: gpt-5.6-luna). Empty uses the Codex CLI default."
  },
  {
    "key": "codex.autoRotate.fiveHourThresholdPercent",
    "type": "number",
    "min": 1,
    "max": 100,
    "default": 100,
    "description": "**Codex 5-hour rotation threshold.** Rotate when the 5-hour window, if Codex reports one, reaches this percentage (usage ≥ threshold). An account can only be switched to while its 5-hour usage is below it. The default 100 rotates only once the window is used up; lower it to leave the account before that."
  },
  {
    "key": "codex.autoRotate.weeklyThresholdPercent",
    "type": "number",
    "min": 1,
    "max": 100,
    "default": 99,
    "description": "**Codex weekly rotation threshold.** Rotate when the weekly (7d) window reaches this percentage (usage ≥ threshold). An account can only be switched to while its weekly usage is below it."
  },
  {
    "key": "codex.autoRotate.strategy",
    "type": "enum",
    "values": [
      "soonestReset",
      "evenPace",
      "leastWaste",
      "sequential"
    ],
    "default": "sequential",
    "description": "**Codex rotation strategy.** Ranks eligible accounts using saved readings, then checks the selected account again before switching. Reset-aware timing also applies to every strategy."
  },
  {
    "key": "codex.autoRotate.trigger",
    "type": "enum",
    "values": [
      "limit",
      "proactive"
    ],
    "default": "limit",
    "description": "**Codex rotation trigger.** When automatic rotation switches accounts."
  },
  {
    "key": "codex.autoRotate.minStayMinutes",
    "type": "number",
    "min": 5,
    "default": 30,
    "description": "**Codex minimum stay before a proactive switch.** Limit-triggered rotation ignores this stay."
  },
  {
    "key": "codex.switchRestartHint",
    "type": "boolean",
    "default": false,
    "description": "After a Codex account switch, warn once per window when this window's Codex extension process started before the switch and offer **Restart extensions**. Off by default: the warning interrupts every window that holds an older Codex process. A running Codex process keeps its login in memory and fails turns once the credential file changes underneath it; VS Code cannot restart a single extension, so restarting the extension host is the lightest repair. Turn this on to be reminded, or enable `#aiUsage.codex.proxy.enabled#` so open chats follow a switch by themselves. New Codex CLI sessions need nothing."
  },
  {
    "key": "codex.proxy.enabled",
    "type": "boolean",
    "default": false,
    "description": "Route the Codex VS Code extension's model calls through a local AI Usage proxy so that switching the Codex authentication profile reaches open Codex chats on their next turn, with no restart. AI Usage adds a `model_providers.ai-usage` entry to Codex's `config.toml` and selects it as `model_provider`; Codex re-reads that file whenever a chat starts. The proxy listens on 127.0.0.1 only, requires a token written into `config.toml`, attaches the login from `auth.json` to each request and forwards it to OpenAI unchanged (ChatGPT logins to the ChatGPT Codex backend, API keys to the OpenAI API). While it is on, Codex's own account panel shows no login, and chats opened before it was enabled keep their previous path until you start a new chat. Turning it off restores `config.toml`."
  },
  {
    "key": "codex.proxy.port",
    "type": "integer",
    "min": 1024,
    "max": 65535,
    "default": 43117,
    "description": "Local TCP port of the service-owned Codex account proxy. Must be an integer from 1024 through 65535. A user-wide ownership lease prevents a second proxy even on a different port. An unrelated listener is reported as a conflict; AI Usage does not silently choose another port. A change updates native routing for new Codex chats."
  },
  {
    "key": "codex.keepAlive.home",
    "type": "string",
    "default": "~/.codex-tmp",
    "description": "Dedicated CLI home for background account checks. Supports ~; relative paths resolve from your user home. Must be separate from the native CLI home."
  },
  {
    "key": "codex.advanced.rotationDiagnostics",
    "type": "boolean",
    "default": false,
    "description": "Advanced: show every saved account’s rotation score, candidate order, eligibility and the reason the current account is kept in the status bar tooltip. Computed by the service when enabled, or by the same shared engine inside VS Code otherwise."
  },
  {
    "key": "codexConfig.agents.maxConcurrentThreadsPerSession",
    "type": "integer",
    "min": 1,
    "nullable": true,
    "default": null,
    "description": "Maximum number of agent threads (the main chat plus its subagents) Codex runs at the same time in one session. Written to `[agents] max_concurrent_threads_per_session` in `config.toml` in the Codex home (`$CODEX_HOME`, default `~/.codex`) when AI Usage starts and whenever this setting changes; Codex reads it when a chat starts. Leave empty (`null`) to keep whatever Codex's `config.toml` already says; clearing the setting later does not remove the value from the file."
  },
  {
    "key": "codexConfig.agents.maxDepth",
    "type": "integer",
    "min": 1,
    "nullable": true,
    "default": null,
    "description": "How deep Codex subagents may nest (a subagent spawning its own subagents). Written to `[agents] max_depth` in Codex's `config.toml`. Leave empty (`null`) to keep whatever Codex's `config.toml` already says; clearing the setting later does not remove the value from the file."
  },
  {
    "key": "codexConfig.agents.jobMaxRuntimeSeconds",
    "type": "integer",
    "min": 1,
    "nullable": true,
    "default": null,
    "description": "Maximum runtime of a Codex agent job, in seconds. Written to `[agents] job_max_runtime_seconds` in Codex's `config.toml`. Leave empty (`null`) to keep whatever Codex's `config.toml` already says; clearing the setting later does not remove the value from the file."
  },
  {
    "key": "copilot.enabled",
    "type": "boolean",
    "default": true,
    "description": "Show live GitHub Copilot premium-request usage for the account Copilot uses in this workspace. When the seat is paid by an organization (or the workspace repository belongs to one of the account's Copilot organizations), the item is labelled with that organization and includes organization-wide figures where permitted."
  },
  {
    "key": "copilot.source",
    "type": "enum",
    "values": [
      "api"
    ],
    "default": "api",
    "description": "Where Copilot usage is read from. The Copilot CLI has no headless usage command, so the service API is the only option."
  },
  {
    "key": "copilot.account",
    "type": "string",
    "default": "",
    "description": "GitHub login whose Copilot usage to show. Leave empty to pick automatically: the signed-in account whose Copilot organization owns the workspace repository, otherwise the first account with a Copilot seat."
  },
  {
    "key": "copilot.checkIntervalMinutes",
    "type": "number",
    "min": 1,
    "default": 5,
    "description": "How often (minutes) the Copilot source is called and the result stored in the shared cache."
  },
  {
    "key": "bridge.modelsEnabled",
    "type": "boolean",
    "default": true,
    "description": "Experimental. Automatically contribute signed-in Codex and Claude CLI models to the Copilot model picker."
  },
  {
    "key": "bridge.autoStart",
    "type": "boolean",
    "default": true,
    "description": "Start the bundled local bridge when model discovery needs it. Reuses an already-running bridge. Discovery checks login without running inference."
  },
  {
    "key": "bridge.codex.persistSessions",
    "type": "boolean",
    "default": false,
    "description": "Save new Codex sessions started through Copilot's CLI bridge in native CLI history (**persistent sessions**), so they can be reopened later. Applies to all clients of this bridge. Disabling affects new sessions and does not delete saved history."
  },
  {
    "key": "bridge.codex.openInCli",
    "type": "boolean",
    "default": false,
    "description": "Show **Open in CLI** and a copyable resume command above the answer as soon as a saved Codex CLI session starts in Copilot. Open after the response finishes. Enable `#aiUsage.bridge.codex.persistSessions#` before creating the session."
  },
  {
    "key": "bridge.codex.openInExtension",
    "type": "boolean",
    "default": false,
    "description": "Show **Open in Codex chat** above the answer as soon as a saved CLI session starts in Copilot. The link opens that session in the native extension, preferring its sidebar. Open after the response finishes. Enable `#aiUsage.bridge.codex.persistSessions#` before creating the session."
  },
  {
    "key": "bridge.codex.sessionDirectory",
    "type": "string",
    "default": "",
    "description": "Absolute workspace directory for new saved Codex sessions on the bridge host. Empty uses this window's workspace when exactly one folder is open, otherwise ~/.cli-byok-bridge/workspaces/codex. Temporary bridge configuration is stored separately."
  },
  {
    "key": "bridge.claude.persistSessions",
    "type": "boolean",
    "default": false,
    "description": "Save new Claude sessions started through Copilot's CLI bridge in native CLI history (**persistent sessions**), so they can be reopened later. Applies to all clients of this bridge. Disabling affects new sessions and does not delete saved history."
  },
  {
    "key": "bridge.claude.openInCli",
    "type": "boolean",
    "default": false,
    "description": "Show **Open in CLI** and a copyable resume command above the answer as soon as a saved Claude Code CLI session starts in Copilot. Open after the response finishes. Enable `#aiUsage.bridge.claude.persistSessions#` before creating the session."
  },
  {
    "key": "bridge.claude.openInExtension",
    "type": "boolean",
    "default": false,
    "description": "Show **Open in Claude Code chat** above the answer as soon as a saved CLI session starts in Copilot. The link opens that session in the native extension, preferring its sidebar. Open after the response finishes. Enable `#aiUsage.bridge.claude.persistSessions#` before creating the session."
  },
  {
    "key": "bridge.claude.sessionDirectory",
    "type": "string",
    "default": "",
    "description": "Absolute workspace directory for new saved Claude sessions on the bridge host. Empty uses this window's workspace when exactly one folder is open, otherwise ~/.cli-byok-bridge/workspaces/claude. Claude extension links require this folder to be open in VS Code. Temporary bridge configuration is stored separately."
  },
  {
    "key": "bridge.url",
    "type": "string",
    "default": "http://127.0.0.1:3210",
    "description": "Loopback address of the standalone CLI subscription bridge."
  },
  {
    "key": "bridge.tokenFile",
    "type": "string",
    "default": "",
    "description": "Local bridge token file. Empty uses ~/.cli-byok-bridge/token on this extension host."
  },
  {
    "key": "bridge.codex.executable",
    "type": "string",
    "default": "codex",
    "description": "Codex CLI executable used by the bundled bridge. Restart the bridge after changing this setting."
  },
  {
    "key": "bridge.claude.executable",
    "type": "string",
    "default": "claude",
    "description": "Claude CLI executable used by the bundled bridge. Restart the bridge after changing this setting."
  },
  {
    "key": "bridge.codex.subagentsEnabled",
    "type": "boolean",
    "default": true,
    "description": "Allow native subagents to delegate work through Copilot’s external tools. Native workspace tools stay disabled. Applies to new workers."
  },
  {
    "key": "bridge.codex.requestTimeoutMinutes",
    "type": "integer",
    "min": 1,
    "max": 1440,
    "default": 60,
    "description": "Maximum minutes for one model request, including native subagent work. Cancellation remains available."
  },
  {
    "key": "bridge.codex.toolTimeoutMinutes",
    "type": "integer",
    "min": 1,
    "max": 1440,
    "default": 60,
    "description": "Minutes to retain a worker while waiting for Copilot to return an external tool result."
  },
  {
    "key": "bridge.claude.subagentsEnabled",
    "type": "boolean",
    "default": true,
    "description": "Allow native subagents to delegate work through Copilot’s external tools. Native workspace tools stay disabled. Applies to new workers."
  },
  {
    "key": "bridge.claude.requestTimeoutMinutes",
    "type": "integer",
    "min": 1,
    "max": 1440,
    "default": 60,
    "description": "Maximum minutes for one model request, including native subagent work. Cancellation remains available."
  },
  {
    "key": "bridge.claude.toolTimeoutMinutes",
    "type": "integer",
    "min": 1,
    "max": 1440,
    "default": 60,
    "description": "Minutes to retain a worker while waiting for Copilot to return an external tool result."
  },
  {
    "key": "history.enabled",
    "type": "boolean",
    "default": true,
    "description": "**Usage history.** The account service records every reading of every saved Claude and Codex account, every account switch (by hand, or by rotation together with the accounts it considered and what it did with each), the rotation sweeps that switched nothing, the stretches with every account at its limit, and checks that start or stop failing, so account use and the rotation rules can be analysed later. **AI Usage: Show Usage History…** and `ai-usage history` summarize a period and export CSV or JSON Lines. One file per month in `#aiUsage.history.directory#`, kept for `#aiUsage.history.retentionDays#`. No login material is recorded. Mirrored to the service's `history.enabled` setting."
  },
  {
    "key": "history.retentionDays",
    "type": "number",
    "min": 1,
    "default": 365,
    "description": "**How long usage history is kept, in days.** A month's file is deleted once the whole month is older than this; 365 keeps a year. Mirrored to the service's `history.retentionDays` setting."
  },
  {
    "key": "history.directory",
    "type": "string",
    "default": "",
    "description": "**Where usage history is written.** Empty: `usage-history` under the account service's home (`~/.ai-usage` on the computer the service runs on, the remote host in a remote session); the history menu shows the path. Supports `~`; a relative path resolves from your user home. Point it at a synced or shared folder to analyse the files elsewhere. A changed directory is used from the next event on; existing files are not moved. Mirrored to the service's `history.directory` setting."
  },
  {
    "key": "mcp.enabled",
    "type": "boolean",
    "default": false,
    "description": "**Experimental.** Offer AI agents an MCP server whose tools list every saved Claude Code and Codex profile with its usage windows and, when `#aiUsage.mcp.switching#` allows, switch the active account. Agents of this VS Code window (Copilot agent mode and every other consumer of the editor's MCP servers) see it as **AI Usage accounts** as soon as this is on; the Claude and Codex Accounts menus register it with their CLIs (**Register the MCP server with the … CLI…**), and other command-line agents register `ai-usage mcp` themselves. Connects to the shared engine running in the background or in VS Code; the bundled MCP adapter needs no service installation. Includes native unsaved-login usage and explicit freshness. Mirrored to the service's `mcp.enabled` setting. See [MCP server for AI agents](https://github.com/p0l0us/ai-usage-vscode-plugin/blob/main/docs/MCP.md)."
  },
  {
    "key": "mcp.switching",
    "type": "boolean",
    "default": true,
    "description": "Let agents change the active account through the MCP server (`switch_account` and `rotate_account`). Off: only the usage tools (`list_accounts` and `refresh_usage`) are offered. Mirrored to the service's `mcp.switching` setting."
  },
  {
    "key": "chatChips.debug",
    "type": "boolean",
    "default": false,
    "description": "Troubleshooting: show a test chip and the chip of every service, including services the current chat does not use (for example Copilot's chip in a Claude chat). If the test chip appears but no service chip does, the extension found no enabled service where it runs (check Output → AI Usage); in the Agents window that is your local computer, even for remote sessions. If a service chip appears only with this on, the agent detection failed for this chat."
  },
  {
    "key": "refreshIntervalMinutes",
    "type": "number",
    "min": 1,
    "description": "Legacy fallback interval (minutes) used when a service has no `checkIntervalMinutes` of its own."
  },
  {
    "key": "accounts",
    "type": "array",
    "default": [
      {
        "name": "Copilot Pro",
        "period": "weekly",
        "usedTokens": 125000,
        "tokenLimit": 500000,
        "usedBudget": 9,
        "budgetLimit": 20
      }
    ],
    "description": "Optional manual account figures. When set, an extra `AI xx%` status bar item shows the remaining share across these accounts."
  }
];
